---
# handlers:
- name: reload sysctl
  ansible.builtin.command:
    cmd:  sysctl --system

- name: Reload nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

# - name: restart containerd
#   systemd:
#     name: containerd
#     state: restarted      
