---
- name: master install kubeadm 
  hosts: ${master_public_ip}
  become: yes  
  become_user: root
  tasks:
  - name: configure dns names for the cluster nodes locally
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        ${master_private_ip}     master
        ${worker1_private_ip}    worker1
        ${worker2_private_ip}    worker2
## if you remove "ansible block begin" and "ansible block ends" ==> ansible will loose track of the file state
  roles:
  - kubernetes-master


- name: worker1 hostname && local dns
  hosts: ${worker1_public_ip}
  become: yes
  tasks:
#  - name: update apt repo & cache
#    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
  - name: Set a hostname
    ansible.builtin.hostname:
      name: worker1
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        ${master_private_ip}     master
        ${worker1_private_ip}    worker1
        ${worker2_private_ip}    worker2

- name: worker2 hostname && local dns
  hosts: ${worker2_public_ip}
  become: yes  
  tasks:
  - name: Set a hostname
    ansible.builtin.hostname:
      name: worker2
  - name: configure dns names for the cluster nodes locally
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        ${master_private_ip}     master
        ${worker1_private_ip}    worker1
        ${worker2_private_ip}    worker2

- name: install kubeadm on both worker nodes
  hosts: ${worker1_public_ip},${worker2_public_ip}
  become: yes
  become_user: root
  gather_facts: no
  roles:
  - kubernetes-worker


- name: master Deploy ingress nginx && myapp
  hosts: ${master_public_ip}
  gather_facts: no
  tasks:
  - name: copy helm values file
    copy:
      src: values.yaml
      dest: /home/ubuntu/myvalues.yaml
  - name: Deploy ingress-nginx controller
    ansible.builtin.command:
      cmd: helm upgrade --install my-nginx-controller ingress-nginx/ingress-nginx -f /home/ubuntu/myvalues.yaml
  - name: copy myapp yaml file
    copy:
      src: myapp.yaml
      dest: /home/ubuntu/myapp.yaml
  - name: Deploy myapp
    ansible.builtin.command:
      cmd: kubectl apply -f /home/ubuntu/myapp.yaml



  # ansible-inventory --list
