---
- name: master install kubeadm 
  hosts: 18.119.162.48
  become: yes  
  tasks:
  - name: update apt repo & cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bash.bashrc
      block: |
        alias c=clear
        alias k=kubectl    
  - name: Set a hostname
    ansible.builtin.hostname:
      name: master
  - name: configure dns names for the cluster nodes locally
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        10.0.1.59     master
        10.0.1.56    worker1
        10.0.1.93    worker2

- name: master_install_kubeadm 
  hosts: 18.119.162.48
  become: yes
  become_user: root
  gather_facts: no   
  roles:
  - kubernetes-master



- name: worker1 instaall kubeadm 
  hosts: 3.138.178.227
  become: yes  
  tasks:
  - name: update apt repo & cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bash.bashrc
      block: |
        alias c=clear
        alias k=kubectl    
  - name: Set a hostname
    ansible.builtin.hostname:
      name: worker1
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        10.0.1.59     master
        10.0.1.56    worker1
        10.0.1.93    worker2

- name: instaall kubeadm 
  hosts: 3.138.178.227    
  become: yes
  become_user: root      
  roles:
  - kubernetes-worker


- name: worker2 instaall kubeadm 
  hosts: 52.15.136.39
  become: yes  
  tasks:
  - name: update apt repo & cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 upgrade=dist
  - name: making some alias
    ansible.builtin.blockinfile:
      path: /etc/bash.bashrc
      block: |
        alias c=clear
        alias k=kubectl    
  - name: Set a hostname
    ansible.builtin.hostname:
      name: worker2
  - name: configure dns names for the cluster nodes locally
    ansible.builtin.blockinfile:
      path: /etc/hosts
      block: |
        10.0.1.59     master
        10.0.1.56    worker1
        10.0.1.93    worker2

- name: instaall kubeadm 
  hosts: 52.15.136.39    
  become: yes
  become_user: root      
  roles:
  - kubernetes-worker


- name: master Deploy ingress nginx 
  hosts: 18.119.162.48
  become: yes  
  become_user: ubuntu
  tasks:
  - name: copy helm value file
    copy:
      src: values.yaml
      dest: /home/ubuntu/myvalues.yaml
  - name: Deploy ingress-nginx repo    
    ansible.builtin.command:
      cmd: helm upgrade --install my-nginx-controller ingress-nginx/ingress-nginx -f /home/ubuntu/myvalues.yaml
  - name: copy myapp yaml file
    copy:
      src: myapp.yaml
      dest: /home/ubuntu/myapp.yaml
  - name: Deploy ingress-nginx repo    
    ansible.builtin.command:
      cmd: kubectl apply -f /home/ubuntu/myapp.yaml


  # - name: output the register variable value
  #   debug:
  #     var:  hostvars['13.50.110.214']['kubeadm_command_output']['stdout']
  
  # ansible-inventory --list
